### ISSUE TITLE
CSS Basic

### ISSUE THREAD

**Issue by welesonbatista** [welesonbatista/iginite-shop#3]
Tasks

- [ ] Seletor CSS
- [ ] Box Model
- [ ] Propriedade `display`
- [ ] Fontes e Textos
- [ ] Web Fonts
- [ ] Cores e Fundos no CSS
- [ ] Especificação de Cores
- [ ] Fundos com CSS
- [ ] Propriedade `background-color`
- [ ] Propriedade `background-image`
- [ ] Propriedade `background-repeat`
- [ ] Propriedade `background-position`
- [ ] Propriedade `background-size`

Links úteis:
[Implementando CSS no projeto](https://app.rocketseat.com.br/classroom/fundamentos-css-2/group/conhecendo-o-css/lesson/adicionando-css-no-html)
[Box Model](https://app.rocketseat.com.br/classroom/fundamentos-css-2/group/box-model/lesson/box-model-1)
[Web Fonts](https://app.rocketseat.com.br/classroom/fundamentos-css-2/group/fontes-e-textos/lesson/web-fonts-1)
[Revisão Flex CSS](https://app.rocketseat.com.br/classroom/avancando-no-html-e-css-2/group/css-flexbox/lesson/revisao-e-propriedades-extras-flex-flow-align-items-row-e-column-gap)  
[Revisão Grid CSS](https://app.rocketseat.com.br/classroom/avancando-no-html-e-css-2/group/css-grid/lesson/shorthand-grid-template)

**Comment by welesonbatista** [comment]
**CSS** (Cascading Style Sheets) é uma linguagem declarativa que controla a apresentação visual de páginas web em um navegador.

O **seletor CSS** é parte da regra do CSS que lhe permite selecionar qual elemento(s) vai receber o estilo pela regra.

```html
<div>Eu estou dentro do elemento.</div>
<p>Eu estou dentro de um elemento de parágrafo.</p>
```

```css
div { color: green }
p { color: red }
```

---
### **Box Model**
O **Box Model** define como o navegador renderiza os elementos HTML, considerando suas propriedades de conteúdo, borda, preenchimento e margem.

|**Propriedade**|**Descrição**|
|---|---|
|**`content`**|A área onde o conteúdo é exibido (texto, imagens, etc.).|
|**`padding`**|Espaço entre o conteúdo e a borda do elemento.|
|**`border`**|Linha ao redor do conteúdo e do preenchimento (padding).|
|**`margin`**|Espaço externo ao redor da borda, separando o elemento dos outros.|

<img src="https://hermes.dio.me/articles/cover/bc77d880-2cfa-4f01-81b5-012f08d572d3.png">

```css
div {
  width: 200px;
  height: 100px;
  padding: 20px;
  border: 5px solid black;
  margin: 15px;
}
```

---
### **Propriedade `display`**
Controla como os elementos HTML são exibidos na página:

| **Valor**          | **Descrição**                                                        |
| ------------------ | -------------------------------------------------------------------- |
| **`block`**        | O elemento ocupa toda a largura disponível e inicia uma nova linha.  |
| **`inline`**       | O elemento ocupa apenas o espaço necessário e não quebra a linha.    |
| **`inline-block`** | Similar ao `inline`, mas permite definir dimensões (width e height). |
| **`none`**         | O elemento é ocultado (não ocupa espaço na página).                  |

<img src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*dwcWnf3ArsatTs5VG7h64w.png">

---
### **Fontes e Textos**
O CSS oferece diversas propriedades para estilizar textos e fontes:

|**Propriedade**|**Descrição**|**Exemplo**|
|---|---|---|
|**`font-family`**|Define a fonte do texto.|`font-family: Arial, sans-serif;`|
|**`font-size`**|Ajusta o tamanho do texto.|`font-size: 16px;`|
|**`font-style`**|Aplica estilos como itálico.|`font-style: italic;`|
|**`font-weight`**|Controla a espessura da fonte (ex.: normal, bold).|`font-weight: bold;`|
|**`color`**|Define a cor do texto.|`color: blue;`|
|**`text-transform`**|Controla a capitalização do texto (ex.: uppercase, lowercase, capitalize).|`text-transform: uppercase;`|
|**`text-decoration`**|Adiciona ou remove decorações (ex.: underline, line-through).|`text-decoration: underline;`|
|**`text-align`**|Alinha o texto (ex.: left, center, right).|`text-align: center;`|
|**`line-height`**|Ajusta o espaçamento entre linhas de texto.|`line-height: 1.5;`|
|**`letter-spacing`**|Define o espaçamento entre letras.|`letter-spacing: 2px;`|
|**`word-spacing`**|Define o espaçamento entre palavras.|`word-spacing: 5px;`|


```css
h1 {
  font-family: "Arial", sans-serif;
  font-size: 24px;
  color: darkblue;
  text-transform: uppercase;
  text-align: center;
  line-height: 1.5;
}
```

---
### **Web Fonts**

Web Fonts permitem utilizar fontes personalizadas hospedadas online, carregadas dinamicamente na página.  
Para usá-las, utilize o serviço **Google Fonts** como exemplo:

**HTML:**

```html
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
```

**CSS:**

```css
body {
  font-family: 'Roboto', sans-serif;
}
```

---

### Cores e fundos

**Comment by welesonbatista** [comment]
## **CSS Flexbox - Layout Flexível**
**CSS Flexbox** (ou **Flexible Box Layout**) transforma um contêiner em um **Flex Container**, fazendo com que seus elementos filhos se tornem **Flex Items**. Isso permite alinhar e distribuir os itens de forma eficiente.

### **Container, Itens e Eixo**

O modelo **Flexbox** é composto por três componentes principais:

- **Container Flex**: O elemento pai que contém os itens flexíveis.
- **Itens Flex**: Os elementos dentro do contêiner que são organizados e manipulados.
- **Eixo (Axis)**:
    - **Eixo principal (Main Axis)**: O eixo no qual os itens são alinhados, que pode ser horizontal ou vertical.
    - **Eixo transversal (Cross Axis)**: O eixo perpendicular ao principal, usado para o alinhamento vertical (se o eixo principal for horizontal) ou horizontal (se o eixo principal for vertical).

<img src="https://css-tricks.com/wp-content/uploads/2018/11/00-basic-terminology.svg">

---

### **Propriedades para o Elemento Pai (Flex Container)**

#### **`display: flex`**

Define o contêiner como um **flex container**, fazendo com que seus filhos se tornem **itens flexíveis**.  

```css
.container {
  display: flex;
}
```

#### **`flex-direction`**
Controla a direção do eixo principal (definindo como os itens serão alinhados).

|**Valor**|**Descrição**|
|---|---|
|`row`|Alinha os itens horizontalmente (padrão).|
|`column`|Alinha os itens verticalmente.|
|`row-reverse`|Alinha os itens horizontalmente, invertido.|
|`column-reverse`|Alinha os itens verticalmente, invertido.|

<img src="https://css-tricks.com/wp-content/uploads/2018/10/flex-direction.svg">

#### **`flex-wrap`**
Determina se os itens devem **quebrar a linha** (se o espaço for insuficiente).

|**Valor**|**Descrição**|
|---|---|
|`nowrap`|Os itens permanecem em uma única linha (padrão).|
|`wrap`|Os itens são distribuídos em várias linhas.|
|`wrap-reverse`|Os itens são distribuídos em várias linhas, mas na ordem invertida.|

<img src="https://css-tricks.com/wp-content/uploads/2018/10/flex-wrap.svg">

---

### **Propriedades dos Itens Flex**

#### **`justify-content`**
Define como os itens flexíveis são distribuídos ao longo do **eixo principal**.

|**Valor**|**Descrição**|
|---|---|
|`flex-start`|Alinha os itens no início do contêiner (padrão).|
|`flex-end`|Alinha os itens no final do contêiner.|
|`center`|Centraliza os itens no contêiner.|
|`space-between`|Distribui os itens com o maior espaço possível entre eles.|
|`space-around`|Distribui os itens com espaços iguais ao redor de cada item.|
|`space-evenly`|Distribui os itens com espaços iguais entre eles.|

<img src="https://css-tricks.com/wp-content/uploads/2018/10/justify-content.svg">

#### **`align-items`**
Define o alinhamento dos itens ao longo do **eixo transversal**.

| **Valor**    | **Descrição**                                                 |
| ------------ | ------------------------------------------------------------- |
| `flex-start` | Alinha os itens no início do eixo transversal.                |
| `flex-end`   | Alinha os itens no final do eixo transversal.                 |
| `center`     | Centraliza os itens no eixo transversal.                      |
| `baseline`   | Alinha os itens pela linha de base do texto.                  |
| `stretch`    | Estica os itens para ocupar todo o eixo transversal (padrão). |

<img src="https://css-tricks.com/wp-content/uploads/2018/10/align-items.svg">

#### **`align-content`**

Alinha as **linhas** de itens ao longo do eixo transversal. Só funciona quando os itens ocupam mais de uma linha.

| **Valor**    | **Descrição**                                                 |
| ------------ | ------------------------------------------------------------- |
| `flex-start` | Alinha os itens no início do eixo transversal.                |
| `flex-end`   | Alinha os itens no final do eixo transversal.                 |
| `center`     | Centraliza os itens no eixo transversal.                      |
| `baseline`   | Alinha os itens pela linha de base do texto.                  |
| `stretch`    | Estica os itens para ocupar todo o eixo transversal (padrão). |

<img src="https://css-tricks.com/wp-content/uploads/2018/10/align-content.svg">
### **Resumo das Propriedades Flexbox**

|**Propriedade**|**Descrição**|
|---|---|
|`display: flex`|Define o contêiner como flexível.|
|`flex-direction`|Controla a direção do eixo principal (row, column, etc.).|
|`justify-content`|Alinha os itens ao longo do eixo principal.|
|`align-items`|Alinha os itens ao longo do eixo transversal.|
|`gap`|Define o espaçamento entre os itens.|
|`flex-wrap`|Define se os itens devem se mover para a linha seguinte.|
|`flex-grow`|Define a proporção de crescimento dos itens.|
|`flex-shrink`|Define a proporção de encolhimento dos itens.|

---


## **CSS Grid Layout**

O **CSS Grid Layout** é uma técnica poderosa para criar layouts bidimensionais, permitindo controlar tanto as linhas quanto as colunas de um contêiner. 

### **Propriedades do Grid Container**

|**Propriedade**|**Descrição**|**Valores Possíveis**|
|---|---|---|
|`display: grid`|Define o contêiner como um grid.|`grid`|
|`grid-template-columns`|Define as **colunas** da grid.|`1fr`, `px`, `%`, `auto`, etc.|
|`grid-template-rows`|Define as **linhas** da grid.|`100px`, `1fr`, `auto`, etc.|
|`grid-template-areas`|Define uma estrutura nomeada para as áreas do grid.|Strings que representam a estrutura do grid (ex: `"header header header" "main sidebar footer"`).|

#### **`grid-template-columns`**
Define o número de **colunas** e suas larguras dentro do grid. Os valores podem ser definidos em unidades como `fr`, `px`, `%`, etc.
- **`fr`** (fração): Divide o espaço disponível entre as colunas de forma proporcional.

```css
.container {
  display: grid;
  grid-template-columns: 1fr 2fr 1fr; /* 3 colunas com larguras proporcionais */
}
```

#### **`grid-template-rows`**
Define o número de **linhas** e suas alturas dentro do grid. Semelhante a `grid-template-columns`, você pode usar valores em `px`, `fr`, etc.

```css
.container {
  display: grid;
  grid-template-rows: 100px 200px; /* 2 linhas com alturas fixas */
}
```

#### **`grid-template-areas`**
Permite definir uma **estrutura nomeada** para as áreas do grid, tornando o layout mais legível e fácil de manipular. Exemplo:

```css
.container {
  display: grid;
  grid-template-areas: 
    "header header header"
    "main sidebar footer"
    "footer footer footer";
}
```

---

### **Posicionamento de Itens no Grid**

#### **`grid-column`**
Define em qual **coluna** o item deve começar e terminar dentro da grade. Exemplo:

```css
.item {
  grid-column: 1 / 3; /* O item ocupa da coluna 1 até a coluna 3 */
}
```

#### **`grid-row`**
Define em qual **linha** o item deve começar e terminar dentro da grade. Exemplo:

```css
.item {
  grid-row: 1 / 2; /* O item ocupa da linha 1 até a linha 2 */
}
```

#### **Shorthand (`grid-area`)**
A propriedade **`grid-area`** é uma forma abreviada de definir **`grid-column`** e **`grid-row`** ao mesmo tempo, utilizando a notação `start` / `end`. Exemplo:

```css
.item {
  grid-area: 1 / 1 / 3 / 3; /* O item ocupa da linha 1 até a 3, e da coluna 1 até a 3 */
}
```

---

### **Propriedades de Alinhamento**

#### **Introdução aos Alinhamentos**

O **CSS Grid** permite controlar o alinhamento dos itens de maneira precisa, tanto no eixo principal quanto no eixo transversal. A seguir, detalharemos como usar essas propriedades de alinhamento.

#### **`align-items`**
Controla o alinhamento dos itens **ao longo do eixo transversal** (vertical, caso o eixo principal seja horizontal).

| **Valor**    | **Descrição**                                                  |
| ------------ | -------------------------------------------------------------- |
| `flex-start` | Alinha os itens no início do eixo transversal (vertical).      |
| `flex-end`   | Alinha os itens no final do eixo transversal (vertical).       |
| `center`     | Centraliza os itens ao longo do eixo transversal (vertical).   |
| `stretch`    | Estica os itens para ocupar todo o espaço disponível (padrão). |

```css
.container {
  display: grid;
  align-items: center; /* Alinha os itens verticalmente no centro */
}
```

#### **`justify-items`**
Controla o alinhamento dos itens **ao longo do eixo principal** (horizontal, caso o eixo principal seja `row`).

| **Valor**    | **Descrição**                                                |
| ------------ | ------------------------------------------------------------ |
| `flex-start` | Alinha os itens no início do eixo principal (horizontal).    |
| `flex-end`   | Alinha os itens no final do eixo principal (horizontal).     |
| `center`     | Centraliza os itens ao longo do eixo principal (horizontal). |
| `stretch`    | Estica os itens para preencher o espaço disponível (padrão). |

```css
.container {
  display: grid;
  justify-items: center; /* Centraliza os itens horizontalmente */
}
```

#### **`align-self`**
Permite que um **item específico** seja alinhado de maneira diferente dos outros itens, ao longo do eixo transversal.

| **Valor**    | **Descrição**                                              |
| ------------ | ---------------------------------------------------------- |
| `auto`       | Usa o valor de `align-items` do contêiner.                 |
| `flex-start` | Alinha o item no início do eixo transversal (vertical).    |
| `flex-end`   | Alinha o item no final do eixo transversal (vertical).     |
| `center`     | Centraliza o item ao longo do eixo transversal (vertical). |
| `stretch`    | Estica o item para preencher o espaço disponível (padrão). |

```css
.item {
  align-self: flex-end; /* Alinha este item no final do eixo transversal */
}
```

#### **`justify-self`**
Permite que um **item específico** seja alinhado de maneira diferente dos outros itens, ao longo do eixo principal.

| **Valor**    | **Descrição**                                              |
| ------------ | ---------------------------------------------------------- |
| `auto`       | Usa o valor de `justify-items` do contêiner.               |
| `flex-start` | Alinha o item no início do eixo principal (horizontal).    |
| `flex-end`   | Alinha o item no final do eixo principal (horizontal).     |
| `center`     | Centraliza o item ao longo do eixo principal (horizontal). |
| `stretch`    | Estica o item para preencher o espaço disponível (padrão). |

```css
.item {
  justify-self: center; /* Centraliza este item ao longo do eixo principal */
}
```

---

### **Propriedades de Grid Auto**

#### **`grid-auto-rows`**
Define a altura das **linhas automáticas** criadas quando o número de itens excede o número de linhas definidas no grid.

```css
.container {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  grid-auto-rows: 100px; /* Cria linhas automáticas com 100px de altura */
}
```

#### **`grid-auto-columns`**
Define a largura das **colunas automáticas** criadas quando o número de itens excede o número de colunas definidas no grid.

```css
.container {
  display: grid;
  grid-template-rows: 100px;
  grid-auto-columns: 150px; /* Cria colunas automáticas com 150px de largura */
}
```

#### **`grid-auto-flow`**
Define como os itens devem ser posicionados automaticamente quando não há espaço definido no grid.

| **Valor** | **Descrição**                                                               |
| --------- | --------------------------------------------------------------------------- |
| `row`     | Posiciona os itens nas linhas, da esquerda para a direita (padrão).         |
| `column`  | Posiciona os itens nas colunas, de cima para baixo.                         |
| `dense`   | Preenche as lacunas na grade com itens menores, otimizando o uso do espaço. |

```css
.container {
  display: grid;
  grid-auto-flow: row dense; /* Preenche as lacunas na grade com itens automaticamente */
}
```

---

### **Resumo das Propriedades do CSS Grid**

|**Propriedade**|**Descrição**|
|---|---|
|`display: grid`|Define o contêiner como um grid.|
|`grid-template-columns`|Define as **colunas** da grid.|
|`grid-template-rows`|Define as **linhas** da grid.|
|`grid-template-areas`|Define uma estrutura nomeada para as áreas do grid, facilitando o layout.|
|`grid-column` e `grid-row`|Define onde os itens começam e terminam em relação às linhas e colunas da grid.|
|`grid-area`|Shorthand para combinar `grid-column` e `grid-row`.|
|`justify-items`|Alinha os itens ao longo do eixo **principal**.|
|`align-items`|Alinha os itens ao longo do eixo **transversal**.|
|`justify-self`|Alinha um item individual ao longo do eixo **principal**.|
|`align-self`|Alinha um item individual ao longo do eixo **transversal**.|
|`grid-auto-rows`|Define a altura das linhas automáticas.|
|`grid-auto-columns`|Define a largura das colunas automáticas.|
|`grid-auto-flow`|Controla como os itens são automaticamente posicionados.|
|`gap`|Define o espaço entre as células do grid.|


[Revisão Flex CSS](https://app.rocketseat.com.br/classroom/avancando-no-html-e-css-2/group/css-flexbox/lesson/revisao-e-propriedades-extras-flex-flow-align-items-row-e-column-gap)
[Revisão Grid CSS](https://app.rocketseat.com.br/classroom/avancando-no-html-e-css-2/group/css-grid/lesson/shorthand-grid-template)
